### ISSUE TITLE
 Name button

### ISSUE THREAD

**Issue by williamsonego** [kosmodrey/telebot#15]
Hi,

I would like to change the name of the buttons , so that when the user clicks the button is passed to the BOT button command .

Example
```
...

bot.on('/buttons', msg => {

	
  let markup = bot.keyboard([
    [bot.button ('/ex1','/ex1'), bot.button('/ex2', '/ex2')],

...

```

necessary that the button is called button1 and the command to be sent is /ex1
There is this possibility ?

Thank you

**Comment by kosmodrey** [comment]
Hi,

At this moment Telegram Bot API [does not support](https://core.telegram.org/bots/API#keyboardbutton) button names with custom callbacks. You can use [inline buttons with "cmdbutton" module](https://github.com/kosmodrey/telebot/blob/master/examples/module-cmdbutton.js) instead.

**Comment by williamsonego** [comment]
Thanks for return = )

It would be possible to use the cmdButton module with the buttons without inline ?

**Comment by kosmodrey** [comment]
Unfortunate, no. Keyboard buttons do not have callbacks (only sends a text message when the button is pressed).

But you can do something like this:

```js
bot.on('/start', msg => {
  // Keyboard markup
  let markup = bot.keyboard([
    ['Button1'],
  ], { resize: true });
  return bot.sendMessage(msg.from.id, 'Keyboard button.', { markup });
});

bot.on('text', (msg, props) => {
  // Button name text
  if (msg.text == 'Button1') {
    // Call /hello command
    return bot.event('/hello', msg, props);
  }
  return bot.sendMessage(msg.from.id, msg.text);
});

bot.on('/hello', msg => {
  return bot.sendMessage(msg.from.id, 'Hello, Command!');
});
```

**Comment by williamsonego** [comment]
kosmodrey again thank you for your attention ... now , as I would to enter a sub- menu buttons ?

EX : button1 >> by clicking the button appear the buttons 2 and 3

**Comment by kosmodrey** [comment]
You can do something like this:

```js
// Navigation button names
const mainBtn = 'Open sub-buttons';
const backBtn = 'Back to main menu';

// Main menu buttons
const mainButtons = bot.keyboard([
    [mainBtn]
  ], { resize: true });

// Sub-menu buttons
const subButtons = bot.keyboard([
    ['Button1', 'Button2'],
    [backBtn]
  ], { resize: true });

// On start, send a main menu markup
bot.on('/start', msg => {
  let markup = mainButtons;
  return bot.sendMessage(msg.from.id, 'Hello!', { markup });
});

// On text, check if it's a button name
bot.on('text', (msg, props) => {
  if (msg.text == mainBtn) {
    // Main button clicked, send a sub-menu markup
    return bot.sendMessage(msg.from.id, 'Sub-menu', { markup: subButtons });
  } else if (msg.text == backBtn) {
    // Back button clicked, send a main menu markup
    return bot.sendMessage(msg.from.id, 'Main menu', { markup: mainButtons });
  }
});
```

**Comment by williamsonego** [comment]
Perfect! It Works very well =)

Thanks a lot kosmodrey
