### ISSUE TITLE
acess list

### ISSUE THREAD

**Issue by williamsonego** [kosmodrey/telebot#16]
Hello Kosmodrey,

How could I create a way to only users listed by name @example in a TXT file would have access to start the bot ? And if the user does not have the list , appear a message Access denied .

I have an example?

**Comment by kosmodrey** [comment]
Hello, William!

You can do something like this:
```js
// Prepeare our access list (load from file, etc.)
const accessList = [
  'user',
  'kosmodrey',
  'tester'
];

// On every text message
bot.on('text', msg => {

  // Get id and username
  let { id, username } = msg.from;

  // Check if username in access list
  let isInList = accessList.includes(username);

  if (isInList) {
    return bot.sendMessage(id, `Hello, ${ username }!`);
  } else {
    return bot.sendMessage(id, 'Access denied!');
  }

});
```

**Comment by williamsonego** [comment]
Thanks a lot for the help and experience of knowing someone who can make a difference in the world!
If you want , you can add me in the telegram to talk more about Bots @wrodrigues_SMK
