### ISSUE TITLE
Override 'text' event

### ISSUE THREAD

**Issue by kenanchristian** [kosmodrey/telebot#17]
i got two events, one for `/hello` command, and one for text message type. But every time i use the `/hello` command, the response from text events also called. How can i avoid this?

**Comment by kosmodrey** [comment]
Hey!

Telegram message type have [entities field](https://core.telegram.org/bots/api#message). You can check for ` bot_command` type to detect commands (best way).

```
bot.on(['/hello', 'text'], msg => {
  let command = isCommand(msg);
  return bot.sendMessage(msg.from.id, `Is bot command: ${command}`);
});


function isCommand(msg) {
  if (msg && msg.entities && msg.entities.length) {
    for (let entity of msg.entities) {
      if (entity.type == 'bot_command') return true;
    }
  }
  return false;
}
```

Or just check if text starts with `/` (lazy way) :smile:

```
bot.on(['/hello', 'text'], msg => {
  let command = msg.text.startsWith('/');
  return bot.sendMessage(msg.from.id, `Is bot command: ${command}`);
});
```

**Comment by kosmodrey** [comment]
Oh, I forgot that TeleBot have info (second) parameter with type of event.

You can check that parameter to detect type of message:
```js
bot.on(['/hello', 'text'], (msg, info) => {
  let command = info.type == 'command';
  return bot.sendMessage(msg.from.id, `Is bot command: ${command}`);
});
```

**Comment by kenanchristian** [comment]
@kosmodrey I'm using the telegram way now. Because the info param also detect my command as a text, not command :(
Great package btw! :grin:

**Comment by kosmodrey** [comment]
Maybe there is a bug, I'll take a look. Thanks.

**Comment by kenanchristian** [comment]
@kosmodrey you're welcome ! :grin:
