### ISSUE TITLE
channel created and info about channel

### ISSUE THREAD

**Issue by abdoljabbar** [kosmodrey/telebot#21]
hi.tnx in advance for ur amazing telebot.
in message event we have 'channelCreated' event.i think that it doesn't work properly.what is that and how to  use it.
suppose my bot added to channel how can i access to their info like admin user, membercount, title,...
how can i authorize admin user of channel send pv to  me.

**Comment by kosmodrey** [comment]
Hello!

Event `channelCreated` is triggered when bot is joined to a new channel. From this event you can get only chat id, title and group type: `chat: { id: -113839907, title: 'test2', type: 'group' }`. To get full channel details use [`getChat(<chat_id>)`](https://github.com/kosmodrey/telebot#getchatchat_id) method.

To get chat administrators - [`getAdmins(<chat_id>)`](https://github.com/kosmodrey/telebot#getchatadministrators-as-getadminschat_id) and for members - [`countMembers(<chat_id>)`](https://github.com/kosmodrey/telebot#getchatmemberscount-as-countmemberschat_id)

**Comment by abdoljabbar** [comment]
channelCreated not triggered for me, but i found another way to get channel info and therefor get channel admin.
it's  simple just replace chat id with channel id that start with @.
getChat(@channel_id) for channel info
and getAdmin(@channel_id) for it's admin
tnx
