### ISSUE TITLE
keyboardbutton on chat when pressed

### ISSUE THREAD

**Issue by frengkys** [kosmodrey/telebot#24]
is it possible when i click button then what i press is show on chat field, 
for example 
if there is a button keyboard [1] [2] [3]
when i click on [1], 1 is shown on chat field not on chat screen as default
and when i click [3][2][1], chat field become 321 and when i press enter 321 is shown 
on the screen...
and is it possible?
@kosmodrey @G07cha @Pyriaxis

**Comment by G07cha** [comment]
If I understood you correctly, you're talking about reply markup. The [official documentation](https://core.telegram.org/bots#keyboards) says:
> Tapping any of the buttons will immediately send the respective command.

Therefore it's impossible for now.

**Comment by frengkys** [comment]
ahhhh, thats why...
thankyou @G07cha

**Comment by frengkys** [comment]
how about change input keyboard on mobile become number ? is it possible?

**Comment by G07cha** [comment]
Do you mean custom keyboard with numbers only? If so, yes it's possible but again, all tapped characters will be sent immediately, so there is no way to type math expression or phone number using reply keyboard for now.

But I think this trick could be achieved with inline keyboard and message editing, so you're sending let's say template message with an inline keyboard which supplied with callback query (callback query won't be displayed in chat) and then, edits template message with new content. Let me know if you need a code example of this trick.
