### ISSUE TITLE
how to get contact number with bot.on event 'contact' ?

### ISSUE THREAD

**Issue by frengkys** [kosmodrey/telebot#27]
how can i get user phone number with bot on event contact ? 
is it a way to get it ?

bot.on('contact', (msg,info)=>{
  const id = msg.from.id;
  let day = msg.text;
  console.log(info);
     return  bot.sendMessage(
        id, 'thanks for contact number'
    );
});

**Comment by kosmodrey** [comment]
Hey, like this:

```js
bot.on('contact', msg => {
  let phoneNumber = msg.contact.phone_number;
  return bot.sendMessage(msg.from.id, `Contact phone number: ${ phoneNumber }`);
});
```

**Comment by frengkys** [comment]
ahhhh, great! Thanks a lot! @kosmodrey
