### ISSUE TITLE
Node 0.10.33

### ISSUE THREAD

**Issue by s-a-y** [kosmodrey/telebot#3]
I did also another change to the code, which adds support for older node.
Do you need it? It uglifies the code a bit and adds dependency to Promise library

**Comment by kosmodrey** [comment]
I was planning to move forward an update code at least to Node.js v4.2.2 (Long Term Support) which have bunch of ES6 features.

Is there any problems to upgrade Node.js to latest LTS version on personal\production server?

**Comment by s-a-y** [comment]
No worries, I can keep it in my repo. I'm just using hosting which only supports Node 0.10.33 at the moment, it's easier for me to modify few lines of code, than migrate to another hosting.
