### ISSUE TITLE
' instead of ` for Europe

### ISSUE THREAD

**Issue by diego77777** [kosmodrey/telebot#33]
Hello, in Europe we don't have on keyboard the ` key, we just have ' or " ...is there a way to let strings like

Hello, ${ firstName } ${ lastName }!

work?

I tried with
` 'Hello, '+${ firstName }!`
and
`'Hello, ${ firstName }!'`

but it doesn't work!

**Comment by kosmodrey** [comment]
Hi,

You can avoid [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) if you wish, like this:

```js
console.log("Hello, " + firstName + "!");
```

> in Europe we don't have on keyboard the ` key, we just have ' or "...

BTW, grave accent is [on every keyboard](https://www.google.com/search?q=grave+accent+on+keyboard&sqi=2) :-)

**Comment by matteocontrini** [comment]
@kosmodrey not really, for example in Italian the grave accent is put above the letters, so we have `è` on the keyboard but not the ` key because we never use it.
Anyway, this shouldn't even be an issue on this repo :P

**Comment by deksden** [comment]
@matteocontrini : MacBook with Russian layout have separate key for ` on keyboard. Think of it as a Russian kontr-sanctions ;-)
