### ISSUE TITLE
Documentation on npmjs.com is outdated

### ISSUE THREAD

**Issue by Vashiru** [kosmodrey/telebot#34]
I just noticed that the documentation on https://www.npmjs.com/package/telebot is outdated. The code example still shows 'pooling' instead of polling despite it already being updated here. There might be more differences but this was the one I noticed.

**Comment by kosmodrey** [comment]
NPM repo has stable version of TeleBot. Yes, we need to release a new 1.0.7 version with recent changes.

**Comment by kosmodrey** [comment]
Updated to 1.0.7 🌞
