### ISSUE TITLE
disable_web_preview on sendMessage is missing

### ISSUE THREAD

**Issue by Vashiru** [kosmodrey/telebot#38]
Telegram has a parameter for the send message function that prevents links from showing the thumbnail and description when in a message. This can be set by sending disable_web_preview: true along with sendMessage. Telebot currently doesn't seem to support this.

API documentation: https://core.telegram.org/bots/api#sendmessage

**Comment by kosmodrey** [comment]
Hi. Use `preview` parameter.

```js
bot.sendMessage(id, 'Google: https://google.com', { preview: false });
```

**Comment by Vashiru** [comment]
Created a pull request #39 to add it to the documentation. :)

**Comment by kosmodrey** [comment]
Thank you :)
