### ISSUE TITLE
Local testing

### ISSUE THREAD

**Issue by n30nl1ght** [kosmodrey/telebot#44]
I write the bot on my computer.
How i can the bot testing local on my computer?

![image](https://cloud.githubusercontent.com/assets/15847494/23294001/99cb27d6-fa69-11e6-956a-6000a1c6b242.png)

here my settings.

**Comment by kosmodrey** [comment]
Hi. If you want to test bot using webhook on localhost, you can use https://ngrok.com or just remove webhook property to run bot using long polling.
