### ISSUE TITLE
How can I get Location data back from a keyboard?

### ISSUE THREAD

**Issue by manishlamichhane** [kosmodrey/telebot#45]
I have a bot that does a series of interaction with the user. The user will first provide some info and as a response to the user reply, my bot asks for location using the button object wrapped inside keyboard object as follows:

```
bot.on('/test', msg => {
  
  let fromId = msg.from.id;
  let firstName = msg.from.first_name;
  let reply = msg.message_id;
  //the bot.keyboard() takes first argument as array of arrays
  let markup = bot.keyboard([[bot.button('location','Send your location')]],"once"); 
  //console.log(markup);
  return bot.sendMessage(fromId, "Send location" , { markup });
});
```

I cannot figure out where can I put the callback method that will get the location sent by the user. I found out that the "update" event can be listened to. But I guess there is a more convenient way of getting this done. Could you please suggest something on this?

**Comment by kosmodrey** [comment]
Hello. Just listen `location` event:
```js
bot.on('location', msg => {
  const {latitude, longitude} = msg.location;
  console.log('Location:', latitude, longitude);
});
```

**Comment by manishlamichhane** [comment]
Great! Thanks!
