### ISSUE TITLE
Possible to get msgid from sendMessage()?

### ISSUE THREAD

**Issue by AWegner1** [kosmodrey/telebot#49]
Hello,

is it possible to get the unique id of a sent message(with a call to sendMessage() ) to for example store it in a database?

thx in advance,
cake

**Comment by kosmodrey** [comment]
Hi,

You can use response of sent message to get unique id:
```js
bot.on('/hello', msg => {
  return bot.sendMessage(msg.from.id, 'Hi').then(response => {
    const messageId = response.result.message_id;
    console.log('Message ID: ' + messageId);
  })
});
```

**Comment by AWegner1** [comment]
Thanks a lot for your amazing fast reply, it works like a charm :))
