### ISSUE TITLE
Keyboard & Button

### ISSUE THREAD

**Issue by Galy4a** [kosmodrey/telebot#7]
Здравствуй,
не мог бы ты привести пример кода для формирования клавиатуры и кнопок, использующий твои кастомные методы?

**Comment by kosmodrey** [comment]
Привет,

В папке [examples](https://github.com/kosmodrey/telebot/tree/master/examples) есть множество примеров, в том числе и пример с клавиатурой и всеми видами кнопок. Его можно посмотреть тут: https://github.com/kosmodrey/telebot/blob/master/examples/keyboard.js

Если есть какие-то конкретные вопросы или непонимания, с радостью помогу разобраться.

**Comment by Galy4a** [comment]
Есть ли возможность создать кнопку команды с произвольным текстом?

**Comment by kosmodrey** [comment]
К сожалению, Telegram не представляет такой возможности, но всегда можно что-нибудь придумать.

Я [написал небольшой модуль](https://github.com/kosmodrey/telebot/blob/master/modules/cmdbutton.js), который вызывает команду если в `callback` кнопки будет прописан текст начинающейся с `/`.

Вот пример:

```js
// Используем наш маленький модуль
bot.use(require('cmdbutton.js'));

// При команде /start
bot.on('/start', msg => {
  
  // Создаём схему кнопок
  let markup = bot.inlineKeyboard([
    [
      // В первом ряду создаём встроенную кнопку с данными "/hello"
      bot.inlineButton('Моя команда', { callback: '/hello' }),
    ],
    [
      // Во втором ряду обычная кнопка с данными
      bot.inlineButton('Обычная кнопка', { callback: 'hello' })
    ]
  ]);

  // Отсылаем сообщение с встроенными кнопками
  return bot.sendMessage(msg.from.id, 'Пример команнрой кнопки.', { markup });

});

// При команде /hello
bot.on('/hello', msg => {
  return bot.sendMessage(msg.from.id, 'Привет!');
});
```

Теперь при нажатии на командную кнопку, будет вызываться обычная команда `/hello`, ей можно придать любой текст.

**Comment by Galy4a** [comment]
Спасибо.
