### ISSUE TITLE
Cannot send image as buffer

### ISSUE THREAD

**Issue by G07cha** [kosmodrey/telebot#9]
When I'm sending the image as buffer server returns 400 code with an error like: "Incorrect format, image must be .png .jpg .tiff...", I've tried to fix it by myself by adding "mime type" and filename with extension but it's didn't worked for me.

Minimum amount of code to reproduce(requies valid image named "node-small.jpg" in "data" folder):
```javascript
const fs = require('fs');

let buffer = fs.readFileSync(`${__dirname}/data/node-small.jpg`);
bot.sendPhoto(USER, buffer).catch(err => console.log(err));
```

**Comment by kosmodrey** [comment]
Hello,

Just add a `fileName` property with a filename and extension: 

```js
bot.sendPhoto(USER, buffer, { fileName: 'node-small.jpg' }).catch(err => console.log(err));
```

Tested, should work.

**Comment by G07cha** [comment]
I also have tried filename but it didn't work well previously but I'll try again tomorrow. I'm not using path or stream because I already receiving image as buffer and saving/reading it will take additional time.

**Comment by G07cha** [comment]
Sorry for late response, you're correct, everything is working.

**Comment by manishlamichhane** [comment]
```
I am facing the same issue. 
var qr = require('qr-image'),
      qr_image_format = 'png',
      qr_png = qr.image(rand_for_qr, { type: qr_image_format }),
      image_folder = './telegram-app/qr-images/',
      qr_image_name = Date.now()+'.'+qr_image_format,
      qr_image_path = image_folder + qr_image_name;
      qr_png.pipe(require('fs').createWriteStream(qr_image_path));

// send QR
      bot.sendPhoto(fromId, qr_image_path , { fileName:qr_image_name }).catch(err => console.log(err));

      // request location
      var response_text = `Dispose. Waste type: `+ waste_type+`. Account balance: `+ balance+ ` Please send your location `;
      var markup = bot.keyboard([[bot.button('location','Send location: ')]],"once"); 
      return bot.sendMessage(fromId, response_text, { markup });

The sendMessage method is working. But the sendPhoto is not. I also checked the image exists in the respective folder. I also get not error message in my console. Any insights in the issue ?

**Comment by G07cha** [comment]
Hi @manishlamichhane, first of all, try to isolate parts, just send a bare image using telegram first, because as I can see, image might not be saved at the time when you call `bot.sendPhoto` method.

**Comment by manishlamichhane** [comment]
Aha! Calling the sendPhoto() method after the 'close' event of write stream did the trick. Thanks man!
